//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: hello_world.proto

package com.vysapp;

@kotlin.jvm.JvmName("-initializehelloRequest")
inline fun helloRequest(block: com.vysapp.HelloRequestKt.Dsl.() -> kotlin.Unit): com.vysapp.HelloRequest =
  com.vysapp.HelloRequestKt.Dsl._create(com.vysapp.HelloRequest.newBuilder()).apply { block() }._build()
object HelloRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.vysapp.HelloRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.vysapp.HelloRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.vysapp.HelloRequest = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.vysapp.HelloRequest.copy(block: com.vysapp.HelloRequestKt.Dsl.() -> kotlin.Unit): com.vysapp.HelloRequest =
  com.vysapp.HelloRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

