//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: hello_world.proto

package com.vysapp;

@kotlin.jvm.JvmName("-initializehelloReply")
inline fun helloReply(block: com.vysapp.HelloReplyKt.Dsl.() -> kotlin.Unit): com.vysapp.HelloReply =
  com.vysapp.HelloReplyKt.Dsl._create(com.vysapp.HelloReply.newBuilder()).apply { block() }._build()
object HelloReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.vysapp.HelloReply.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.vysapp.HelloReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.vysapp.HelloReply = _builder.build()

    /**
     * <code>string message = 1;</code>
     */
    var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 1;</code>
     */
    fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.vysapp.HelloReply.copy(block: com.vysapp.HelloReplyKt.Dsl.() -> kotlin.Unit): com.vysapp.HelloReply =
  com.vysapp.HelloReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

